### ISSUE TITLE
Generate code with proper indentation

### ISSUE THREAD

**Issue by brice-morin** [TelluIoT/ThingML#137]
Though not a big problem for Java, JS and C (code can easily be indented in any IDE), large unindented blocks of code are not so readable e.g. in PlantUML compiler. It might also become an issue the day someone wants to target Python ;-)

**Comment by maxleiko** [comment]
![INDENT§](https://i.imgflip.com/1gauy4.jpg)

**Comment by brice-morin** [comment]
@jakhog has implemented the infrastructure to generate indented code, etc. Go and JS compilers now use it. I suggest the other compilers also use it when they go through a major refactoring. I guess we can close the issue for now.
