### ISSUE TITLE
Checker (or even Parser/Resolver) should check that included Things do not define ports with same names

### ISSUE THREAD

**Issue by brice-morin** [TelluIoT/ThingML#144]
It currently seems very possible (though I have to investigate a bit more) to include two things A and B into a third one, where A and B both define ports that have conflicting names. It does not seem to raise any issue in the parser, the resolvers or the checker. But I guess the end result is somehow random (or not always as intended by the user). This should of course raise a proper error, as soon as possible (ideally directly in parser/resolver).

I guess the same goes for included messages, properties, etc, but I have not tried yet

**Comment by jakhog** [comment]
This is fixed (at least now with the current checker migrations). There are also tests for these cases, which currently fails because the new checker errors are not caught by the compiler. I consider this issue solved.
