### ISSUE TITLE
Arduino "Timer" plugin should not use a HW timer when only soft timers are declared

### ISSUE THREAD

**Issue by ffleurey** [TelluIoT/ThingML#147]
It seems that as soon as the Timer plugin is used, it automatically uses one of the HW timers (whichon can be customized with the annotation @hardware_timer on the connector).

However, it should not use a HW timer is only the soft timers messages are defined. I.e. no messages with @xms_tic "XX" annotation.

**Comment by ffleurey** [comment]
Note: the soft timer make use of millis() and do not need any new timer interrupt to be implemented.

**Comment by brice-morin** [comment]
I assume this issue is now deprecated with the timer in the STL
