### ISSUE TITLE
Disallow multiple connectors with same pair of required-provided ports

### ISSUE THREAD

**Issue by jakhog** [TelluIoT/ThingML#153]
Currently the following code does not produce any errors
```
connector someThing.Port => otherThing.Port
connector someThing.Port => otherThing.Port
```
nor does it for external connectors
```
connector someThing.Port over Protocol
connector someThing.Port over Protocol
```

**In my mind, this should not be valid ThingML code, and should not be allowed by the compiler.**

If it is supposed to be valid, I'm not quite sure what it means. Should you send/receive multiple copies of the same messages?

**Comment by brice-morin** [comment]
IMHO, n-to-m connectors should be allowed except in your very case.
