### ISSUE TITLE
Outline is nearly useless

### ISSUE THREAD

**Issue by brice-morin** [TelluIoT/ThingML#162]
I am not too impressed by the new outline... Either the parser is not working properly, or the outline is not complete, but it seems my models are lacking quite a few elements in the outline, and I cannot see anything in the properties view. Quite annoying, especially as we are migrating to the new parser...

**Comment by ffleurey** [comment]
The EMF "sample reflexive editor" can be used to inspect the models. The outline will be improved later but has no ambition to exhibit the whole model

**Comment by brice-morin** [comment]
@jakhog is working on it and it looks promising :-)

**Comment by brice-morin** [comment]
I did some more work on the outline, resulting in two conflicting visual styles. I suggest we use the black&white icons. But instead of the black, we might use the color of the thingml keyword, so that we can more easily map the concepts between the outline and the model.

**Comment by brice-morin** [comment]
Not 100% perfect, yet. But still acceptable. Closing the issue.
