### ISSUE TITLE
Updatesite doesn't build on the xtext HEAD

### ISSUE THREAD

**Issue by yellowiscool** [TelluIoT/ThingML#181]
Maven fails with the following error : 
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.thingml.eclipse.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: org.thingml.eclipse.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.thingml.eclipse.feature.feature.group [1.0.0,1.0.1)' but it could not be found
```

**Comment by yellowiscool** [comment]
Let's never talk about this anymore.

**Comment by yellowiscool** [comment]
Thanks @ffleurey btw.

**Comment by brice-morin** [comment]
Was the issue between your screen and your chair? :-)

**Comment by yellowiscool** [comment]
I stupidly followed the instructions from the readme. The instructions were wrong, but I should have seen it.

**Comment by jakhog** [comment]
As far as I understood, the instructions in the README.md is for the EMF version, so it should really be fixed on the xtext branch?

**Comment by brice-morin** [comment]
README.md in xtext branch definitely needs some updates. Feel free to contribute :-)
