### ISSUE TITLE
Make ThingML thread safe

### ISSUE THREAD

**Issue by jakhog** [TelluIoT/ThingML#190]
There are some methods/classes that are currently not thread safe. E.g. `ThingMLCompiler.loadModel(...)`, and I'm guessing many more.

IMHO we should aim for thread safety in the compilers (not the EMF models and other dependencies).

My specific problem right now is that I try to run the tests in threads, and if I call `loadModel` at the same time in 8 threads, I get a random set of 8 models returned.

**Comment by yellowiscool** [comment]
Just run 8 VMs instead of 8 threads. 🏖

Le 1 août 2017 12:29 PM, "Jakob Høgenes" <notifications@github.com> a
écrit :
