### ISSUE TITLE
Checker performances issues in eclipse

### ISSUE THREAD

**Issue by ffleurey** [TelluIoT/ThingML#194]
The checker seem to trigger way too often (or take too much time). Working on this project https://github.com/ffleurey/ThingML-PongTutorial in eclipse is almost impossible because for every time on file is checked, all the thingml files in the workspace are re-parsed and checked.
Before the checker was improved to catch more errors, this was not much of a problem. We should: 

1/ Make sure that we do not run the checker more than needed (it may be that xtext default behavior is to re-pared and validate too often) and 

2/ we should use a profiler on the checker to make sure that there are no big inefficiencies in it.

**Comment by brice-morin** [comment]
Yes, I think I have experienced the same issues on the same project :-) I guess the default strategies should be to check on save, or something like this.

Well, the checker is deeply inefficient. Each rule basically re-browse the whole configuration and looks for stuff it is interested in. I think a better approach would be:
- only browse the configuration (and everything it contains or refers to) once
- each rule subscribes to model elements of interests (e.g. functions)
- the main "browser" notifies the rules with only the elements they are interested in
- each rule can just check what it is supposed to check, without the need for it to first find the elements of interests.

**Comment by brice-morin** [comment]
Feel free to fix it, as I cannot allocate time on ThingML anymore... Or maybe I can have a look this weekend if I get bored.

**Comment by brice-morin** [comment]
More than good enough now
