### ISSUE TITLE
Instance initialisation order

### ISSUE THREAD

**Issue by jakhog** [TelluIoT/ThingML#200]
It seems that the tests assume that instances will be initialised in a specific order when there are dependencies between them (in terms of connectors). In my opinion this is not necessary, and does not make a lot of sense.

As long as messages sent from one instance (e.g. in an on entry) is not lost/ignored because other instances are are not _ready yet_, then any order of initialisation should be fine. Right?

In particular, I am talking about these tests:
- [testInstanceInitializationOrder2.thingml](https://github.com/TelluIoT/ThingML/blob/c5a6bd4d09e764ab18c9eefc075404edccf77c13/testing/src/test/resources/tests/General/Others/testInstanceInitializationOrder2.thingml)
- [testInstanceInitializationOrder3.thingml](https://github.com/TelluIoT/ThingML/blob/c5a6bd4d09e764ab18c9eefc075404edccf77c13/testing/src/test/resources/tests/General/Others/testInstanceInitializationOrder3.thingml)
- [testInstanceInitializationOrder4.thingml](https://github.com/TelluIoT/ThingML/blob/c5a6bd4d09e764ab18c9eefc075404edccf77c13/testing/src/test/resources/tests/General/Others/testInstanceInitializationOrder4.thingml)

In my opinion, any order of __ABCDE__ should be allowed as output in these tests (making them useless), and if we want to make sure that messages are not lost during initialisation, we should rather make new tests that check that.

Do you agree?

**Comment by brice-morin** [comment]
Yes, I think the important is not to lose the messages during initialization. Can you write those new tests?
