### ISSUE TITLE
UML State Machine Diagram without the actions

### ISSUE THREAD

**Issue by ffleurey** [TelluIoT/ThingML#209]
Is there an option hidden somewhere to generate the UML state machine diagram without the actions?
I would like to have only the events, probably not even the guards. This is because I want to use the diagrams for documentation and for any thing with more than 3 states, the diagrams with all the info are way too large to be readable.

**Comment by brice-morin** [comment]
Yes, somewhere in the UML compiler and/or the ThingML "pretty printer". AFAIK, those options are not exposed anymore and require to re-compile everything :-)

**Comment by brice-morin** [comment]
We now generate detailed/non detailed versions systematically.
