### ISSUE TITLE
Testing frameworks

### ISSUE THREAD

**Issue by brice-morin** [TelluIoT/ThingML#217]
Seems like we have three testing projects... Are they all needed and used? If not, we should do some cleaning. There is no need to archive old stuff explicitly in a SCM...

**Comment by jakhog** [comment]
Well:
 - I haven't been using them
 - they have not been touched in almost a year
 - they are not built in the main POM

So if none of you other guys are using them, I guess its time to let them go 👋 

Anyways, they will still be kept in the history of the repo, so if anyone needs some pieces of code it will be simple enough to fish back out...

**Comment by brice-morin** [comment]
@jakhog can you then do the cleaning?
