### ISSUE TITLE
Incorrect Sink State Warning

### ISSUE THREAD

**Issue by ffleurey** [TelluIoT/ThingML#219]
Not sure how elaborate we should make the checker or force to put "final" states when there are no transition out a a state but in this example since there are transition out of the parent state, it is not a sink state.

![sinkstate](https://user-images.githubusercontent.com/756491/38083829-0a2f4a0a-334b-11e8-9afe-9bbb99d6680b.png)

**Comment by brice-morin** [comment]
Indeed. The check currently simply looks at states in isolation, without looking at the parent.
