### ISSUE TITLE
Improve code-completion / suggestions in Eclipse

### ISSUE THREAD

**Issue by jakhog** [TelluIoT/ThingML#228]
The code-completion suggestions in Eclipse, are more or less useless at the moment. In some cases it works great (after `=>` in connectors, getting message parameters in the action language, ...) but most of the time, it suggests the full list of keywords.

At least the reachable properties/variables should be at the very top of the list in the action language.

A revision of the current setup would be very good.

**Comment by brice-morin** [comment]
There has been some improvements there lately. Not sure if it is enough though... but feel free to re-open the issue if it was not sufficient.
