### ISSUE TITLE
The brower compiler uses the non standard setImmediate

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#247]
`setImmediate` is a non-standard method only available in Internet Explorer, Edge, and NodeJS. Polyfils such as [YuzuJS/setImmediate](https://github.com/YuzuJS/setImmediate) or [core-js](https://github.com/zloirock/core-js/blob/d42976f7af29832cddc04051cb7032057d17ab74/packages/core-js/internals/task.js) do exist. A `setTimeout` could be used instead, but it may have a 4ms delay.

`requestIdleCallback` and `requestAnimationFrame` are also alternatives to consider but probably not always relevant.

[MDN documentation about setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).

**Comment by brice-morin** [comment]
@fungiboletus if you have some snippets of generated code where is appears, feel free to mention it in this issue

**Comment by fungiboletus** [comment]
Hei @brice-morin 
```
thing HelloThing {
	statechart HelloWorld init Greetings {
		state Greetings {
			transition -> Bye action print "Hello World!\n"
		}
		final state Bye {
			on entry print "Bye.\n"
		}
	}
}

configuration HelloCfg {
	instance my_instance: HelloThing
}
```

**Comment by fungiboletus** [comment]
```javascript
HelloThing.prototype.build = function(session) {
	/*State machine (states and regions)*/
	/*Building root component*/
	this._statemachine = new StateJS.StateMachine('HelloWorld');
	let _initial_HelloThing_HelloWorld = new StateJS.PseudoState('_initial', this._statemachine, StateJS.PseudoStateKind.Initial);
	let HelloThing_HelloWorld_Greetings = new StateJS.State('Greetings', this._statemachine);
	let HelloThing_HelloWorld_Bye = new StateJS.FinalState('Bye', this._statemachine).entry(() => {
		console.log(''+'Bye.\n');
		setImmediate(()=>this._stop());
	});
	_initial_HelloThing_HelloWorld.to(HelloThing_HelloWorld_Greetings);
	HelloThing_HelloWorld_Greetings.to(HelloThing_HelloWorld_Bye).effect(() => {
		console.log(''+'Hello World!\n');
	});
}
```

**Comment by brice-morin** [comment]
ah yes, in final states...

**Comment by brice-morin** [comment]
So something like: `setTimeout(()=>this._stop(),0);` instead?

**Comment by fungiboletus** [comment]
Yes, it works with this fix.
