### ISSUE TITLE
Stackoverflow in the Eclipse editor when the user creates includes cycles in her model

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#255]
In Eclipse, create a new ThingML file and write the following piece of art :

```
thing Canard includes Canard
```

As you finish to write the second `Canard`, you get the following error message:

```
org.eclipse.xtext.validation.CompositeEValidator  - Error executing EValidator

java.lang.StackOverflowError
```

It may also happen when the thing is not a Canard.

**Comment by brice-morin** [comment]
OK, the problem is not in the checker, but in some derived properties not detecting cycles...
