### ISSUE TITLE
How to run the tests ?

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#259]
I'm working on #258 and I would like to run the tests for the NodeJS compiler on my machine.

However I have no idea about how to run the tests. I tried a `mvn clean install` in the `./testing` directory and it failed after 30s.

**Comment by brice-morin** [comment]
OK, first pull my latest changes. I removed `Integer` some time ago because it is ambiguous  (compared to e.g. Int16), but it was quite intensively used in the tests...

you may have to `mvn clean install` in `./testing/framework` and `./testing/reportbuilder` first, then `mvn clean install` in `./testing`

**Comment by brice-morin** [comment]
Also, it is possible to just run the nodejs tests, but I do not remember how...

**Comment by brice-morin** [comment]
or in Eclipse, right click on testing project,-> run as JUnit

**Comment by fungiboletus** [comment]
`cd ./testing/framework && mvn clean install`

```
 Failed to execute goal on project testing.framework: Could not resolve dependencies for project org.thingml:testing.framework:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at org.thingml:compilers.framework:jar:2.0.0-SNAPSHOT -> org.thingml:thingml:jar:2.0.0-SNAPSHOT: Failed to read artifact descriptor for org.thingml:thingml:jar:2.0.0-SNAPSHOT: Could not find artifact org.thingml:language:pom:2.0.0-SNAPSHOT in thingml-snapshot (http://maven.thingml.org/thingml-snapshot/) -> [Help 1]
```

**Comment by fungiboletus** [comment]
I did yesterday, but I just did it again to make sure and it doesn't help.

**Comment by brice-morin** [comment]
Hmmm...

Try also `cd language && mvn clean install`

**Comment by brice-morin** [comment]
well, the errors when compiling `language` are indeed not an issue (or at least not a blocking one).

As for the tests themselves, all the tests for which you have the proper setup to run the generated code (e.g. `node` and `npm` for NodeJS)  should run (the other should be skipped (probably posix, posixmt and go in your case?). Still, most nodejs tests should pass.... Not quite sure what is wrong, thoug... Is there some useful information from the errors and exceptions being displayed in you terminal?

**Comment by fungiboletus** [comment]
Yes, posix and go are skipped. I probably don't have enough storage on my laptop to store the error log. I can't see anything in the terminal history, but this one is quite short. I might try again if I found it the alternative to `tee` in powershell and buy a 2TB SSD.

**Comment by fungiboletus** [comment]
So the powershell equivalent to `tee` is `tee`. Example : `mvn clean install | tee -filepath bigdata.log`.

Using the latest version, by pulling and not fetching (fuck this fetch button on my Git GUI, so stupid), it runs. A few NodeJS tests fails, but that's expected I guess.

**Comment by fungiboletus** [comment]
I also decided to ignore the many `Timeout while executing 'mvn exec:java'` because maven is so slow that it's not relevant.
