### ISSUE TITLE
Couldn't resolve reference to Type 'Integer'

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#262]
I pulled master, ran mvn clean install for hours and finally ran the tests. Many failed on this error.

**Comment by brice-morin** [comment]
That one should be fixed...  [Integers are back in the STL](https://github.com/TelluIoT/ThingML/blob/master/language/thingml/src/org/thingml/stl/datatypes.thingml)

**Comment by fungiboletus** [comment]
Well… Let's not talk about this issue ever 🙈
