### ISSUE TITLE
The JavaScript compiler needs to be updated to support latest version of its state library

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#267]
A major breaking change has been introduced in steelbreeze/state 7.2.0, see steelbreeze/state#12

**Comment by fungiboletus** [comment]
I'm not sure but I feel like the internal events are broken.

**Comment by brice-morin** [comment]
Anyway, since we do not have direct control over steelbreeze/state (though the guy is usually quite reactive at fixing issues), it is probably a good idea to be one minor revision behind in the generated JS code, unless we have a good reason to jump to the last version.

**Comment by mesmo** [comment]
There was a big re-work of transitions - if you have some examples of the issues you're seeing I'll investigate and fix...

**Comment by mesmo** [comment]
I have found a bug in the triggering of completion transitions after internal transition evaluation; v7.2.2 has been released and hopefully cures the issues you are seeing.

**Comment by fungiboletus** [comment]
I confirm the bug has been fixed. We probably should update the generator to the new transition syntax at some point, but that's another issue to track.

Thanks again @mesmo

**Comment by brice-morin** [comment]
Great! Once again, your reactivity on `state` is very much appreciated, @mesmo
