### ISSUE TITLE
How to output unicode characters in generated code?

### ISSUE THREAD

**Issue by brice-morin** [TelluIoT/ThingML#273]
For the UML compiler, I'd like to generate some unicode characters (this is very well supported by plantUML), so as to give more information in the diagrams in a nice way (e.g. using ▶ to denote a received message). I tried different ways, but all I can get is `?` instead of ▶...

**Comment by nharrand** [comment]
How about:

```java
FileUtils.write(new File("test"), " ▶ ",Charset.forName("UNICODE"));
```

```xml
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.5</version>
    </dependency>
```

?
