### ISSUE TITLE
Consider migrating JS compiler towards state lib 8.0.0

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#283]
As stated here in https://github.com/steelbreeze/state/blob/master/RELEASES.md#v800 steelbreeze/state has breaking changes in its 8.0.0 version.

Someone confident with ThingML should probably run the unit tests with this version.

**Comment by brice-morin** [comment]
Do you mean the `package.json` we generate uses by default this new 8.0.0 version? If so, I would first correct that, so as it use a version we know works (in principle, the latest 7.x.y).

Then, we can talk about migrating to 8.x.y :-)

**Comment by fungiboletus** [comment]
No it does not. We should discuss about the migration.

Le jeu. 4 avr. 2019 à 21:15, Brice Morin <notifications@github.com> a
écrit :

**Comment by brice-morin** [comment]
That was what I feared :-)

**Comment by brice-morin** [comment]
OK, work in progress :-)

Quite a big refactoring in the end, but so far I like the new generated code (though it does not work at this very moment, but I am getting closer)
