### ISSUE TITLE
Is there any documentation for protocol keyword for configuration?

### ISSUE THREAD

**Issue by minescoviciu** [TelluIoT/ThingML#285]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My setup is made of a couple of arduinos which are communicating with a raspberry via nRF24L01 radio modules. The code on the arduinos is generated with thingml. I want the raspberry to be a gateway to my web server that will display data captured from the arduinos' sensors. From the examples found on this repository, I couldn't figure it out how the annotations and protocol keyword work. 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Here](https://github.com/TelluIoT/ThingML/blob/master/org.thingml.samples/src/main/thingml/network/_arduino/MQTT/MQTTSrv.thingml), I don't understand how is the connection made between the led_service port and the MQTT broker

Thank you

**Comment by brice-morin** [comment]
The [annotation registry](https://github.com/TelluIoT/ThingML/blob/master/language/thingml/src/org/thingml/annotations/AnnotationRegistry.java) documents (most of) the annotations.
