### ISSUE TITLE
False error :  Expected Object[], assigned with Object

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#289]
```
property canards: Object[] = `[]` as Object[]
```

**Comment by brice-morin** [comment]
Just to be sure, are you using a recent version of ThingML ?

**Comment by brice-morin** [comment]
Nevermind, I reproduced the issue.

**Comment by brice-morin** [comment]
Note that in ThingML, arrays must have a size i.e. `property canards: Object[8] = `[]` as Object[]`

This is a limitation inherited from the Arduino compiler, but should not have any incidence in JS
