### ISSUE TITLE
How to register annotations ?

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#290]
```
Annotation @nodejs_package is not registered. Non-registered annotations will be deprecated in a future version.
```

**Comment by brice-morin** [comment]
You can follow the same procedures as for the others: https://github.com/TelluIoT/ThingML/blob/master/language/thingml/src/org/thingml/annotations/AnnotationRegistry.java

**Comment by fungiboletus** [comment]
I tried without success:

```java
annotations.put("nodejs_package", new Annotation(
		"nodejs_package",
		"If present, the configuration is compiled as a NodeJS NPM package",
		new EClass[] {ThingMLPackage.eINSTANCE.getConfiguration()}
));
```

and

```
configuration  Canard
@nodejs_package
{
...
```

Annotation is still marked as unregistered :(

**Comment by brice-morin** [comment]
Hmmm.... strange. Try compiling from root and from ./language

**Comment by fungiboletus** [comment]
I did. Didn't really mind. However I since rebooted for another reason and I can see that it's working.
