### ISSUE TITLE
http://thingml.org/dist/update2 is not reachable

### ISSUE THREAD

**Issue by easyvolts** [TelluIoT/ThingML#301]
I just tried to access the web page with eclipce pluging http://thingml.org/dist/update2 and it doesn't work.

**Comment by brice-morin** [comment]
This server is down and won't be up any time soon (never). You can find the update sites here: https://github.com/TelluIoT/ThingML/releases (thingml.repository*.zip), which you can download and install in Eclipse using local update site.

**Comment by easyvolts** [comment]
Brice-morin, thank you for the fast response. I'd like to let you know that documentation in this chapter https://github.com/TelluIoT/ThingML#thingml-eclipse-based-ide needs to be fixed to reflect the information from above.
Best regards, Valerii

**Comment by brice-morin** [comment]
Good catch, thanks! It should be fixed now.
