### ISSUE TITLE
Function is never called warning on fragment

### ISSUE THREAD

**Issue by fungiboletus** [TelluIoT/ThingML#306]
I have a thing fragment like this:

```
thing fragment Stuff {
  function doStuff() do
    print "her"
  end
}
```

and another thing using it like this :

```
thing OtherStuff includes Stuff {
  statechart init DoStuff {
    final state DoStuff {
      on entry do
        doStuff()
      end
    }
  }
}
```

Should we have a warning in `doStuff` of `Stuff` since it's a fragment ?

**Comment by brice-morin** [comment]
I fixed the validation rule so that it checks if it is called by "including" things (i.e. any Thing that include the function directly or not).
