### ISSUE TITLE
thing fragments defined in separate files and included one by one are not compiled  

### ISSUE THREAD

**Issue by vassik** [TelluIoT/ThingML#52]
Consider the following three files:

testA.thingml

```
import "../../thingml.thingml"

thing fragment A {

    function a() do
        print "a()\n"
    end
}
```

testB.thingml

```
import "../../thingml.thingml"
import "testA.thingml"


thing fragment B includes A {

    function b() do
        print "b()\n"
        a()
    end
}
```

testC.thingml

```
import "../../thingml.thingml"
import "testB.thingml"

thing fragment C includes B {

    function c() do
        print "c()\n"
        b()
        a()
    end
}

configuration testSeveralFiles {

 instance c : C
}
```

The thing C cannot call a() from A. On attempt to compile, a NULL pointer exception throws...

**Comment by brice-morin** [comment]
Hopefully the new parser solves this issue. @ffleurey ?

**Comment by brice-morin** [comment]
@ffleurey ?

**Comment by jakhog** [comment]
There are tests for this now. The Jenkins seems to be down right now, but at least they pass for Go and NodeJS on my computer. So I'm going to assume that this is fixed.
